version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: base
    volumes:
      - pgdata:/var/lib/postgresql/data

  odoo:
    image: odoo:19
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    command:
      [
        "--",
        "-d",
        "base",
        "--without-demo=all",
        "--proxy-mode",
        "--no-database-list",
      ]
    volumes:
      - odoo_data:/var/lib/odoo
      - extra_addons:/mnt/extra-addons

volumes:
  pgdata:
  odoo_data:
  extra_addons:
